repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint dapp
        args:
          - --max-line-length=90
          - --ignore-imports=yes
          #- -d duplicate-code
        language: python
        types:
          - python 
      - id: black
        name: black
        entry: poetry run black dapp
        language: python
        types:
          - python 

